spring:
  application:
    name: bets
  datasource:
    url: jdbc:h2:mem:sports-management;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  docker:
    compose:
      lifecycle-management: start_only
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: 'com.sportygroup.bets.api'


rocketmq:
  name-server: localhost:9876
  producer:
    group: bets-producer-group


logging:
  level:
    root: info
    org.apache.rocketmq.spring.core: debug
